services:
  app:
    build:
      context: .                    # Current directory
      dockerfile: Dockerfile        # Dockerfile in the same folder
    container_name: app
    ports:
      - "3000:3000"                 # Map local port 3000 to container port 3000
    env_file:
      - ./.env                      # Use the environment variables file
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=PaymentDB
      - DB_PORT=27017

  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - db:/data/db                 # Persistent storage for MongoDB
    ports:
      - "27017:27017"               # Expose MongoDB on local port 27017
    env_file:
      - ./.env

volumes:
  db:                               # Define volume for MongoDB data
