version: '3.8'

services:
    app:
        build: ./management
        container_name:
        image:
        ports:
        volumes:
    
        networks:
        env_file:
          - ./.env
        depend_on:
          - mongodb
        stdin_open: true
        tty: true
        environements:
          - DB_HOST = mongodb
          - DB_USER = $MONGODB_USER
          - DB_PASSWORD = $MONGODB_PASSWORD
          - DB_NAME = $MONGODB_DATABASE
          - DB_PORT = $MONGODB_DOCKER_PORT



    mongodb:
       image: mongo:5.0.2
       restart: unless-stopped
       environment:
        - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
        - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
       volumes:
          - db:/data/db
       env_file:
          - ./.env
       ports: 
          - DB_PORT = $MONGODB_DOCKER_PORT
    

    
volumes:
  db:

      
